version: '3.8'
services:
  dev-db:

    image: postgres:15-alpine
    container_name: dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dev_railswad_db
    ports:
      - "5433:5432"
    volumes:
      - dev_data:/var/lib/postgresql/data
  prod-db:
    image: postgres:15-alpine
    container_name: prod-db
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
      POSTGRES_DB: prod_railswad_db
    ports:
      - "5434:5432"
    volumes:
      - prod_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@railswad.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - dev-db
      - prod-db
  app:
    build: .
    container_name: deliveryservice
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - dev-db
      - prod-db
volumes:
  dev_data:
  prod_data: